---
- hosts: staging
  roles:
    - angstwad.docker.ubuntu
    - docker

- hosts: production
  become: true
  become_user: root
  roles:
    - angstwad.docker.ubuntu
    - docker

- hosts: uat
  become: true
  become_user: root
  roles:
    - angstwad.docker.ubuntu
    - docker

